// src/components/pokemon/encounter_locations/WildPokemon.vue
<template>
  <div class="wild-pokemon">
    <LocationsChart @showLocationDetails="loadLocation($event)" />
    <EncounterDetailsWrapper
      v-if="encounterDetails"
      :encounter="encounterDetails"
    />
    <PokemonDetail
      v-if="pokemonStore.showPokemonDetails"
      :pokemon-id="pokemonStore.pokemonId"
      :is-wild-encounter="true"
    />
  </div>
</template>

<script setup>
import { ref } from "vue";
import { usePokemonStore } from "../../../stores/pokemon";
import LocationsChart from "./LocationsChart.vue";
import EncounterDetailsWrapper from "./EncounterDetailsWrapper.vue";
import PokemonDetail from "./../pokemon_details/PokemonDetail.vue";
import encounters from "./../../../data/encounters";

const pokemonStore = usePokemonStore();
let encounterDetails = ref(encounters[0]);

function loadLocation(locationId) {
  const location = encounters.find((loc) => loc.id === locationId);
  encounterDetails.value = location;
}
</script>

<style lang="scss" scoped></style>

// src/components/pokemon/encounter_locations/WildPokemon.jsx
import { useState } from 'react';
import { usePokemonStore } from '../../../stores/pokemon';
import LocationsChart from './LocationsChart';
import EncounterDetailsWrapper from './EncounterDetailsWrapper';
import PokemonDetail from '../pokemon_details/PokemonDetail';
import encounters from '../../../data/encounters';

export default function WildPokemon() {
  const showDetail = usePokemonStore((s) => s.showDetail);
  const pokemonEntryId = usePokemonStore((s) => s.pokemonEntryId);
  const [encounterDetails, setEncounterDetails] = useState(encounters[0]);

  function loadLocation(locationId) {
    const location = encounters.find((loc) => loc.id === locationId);
    setEncounterDetails(location);
  }

  return (
    <div className="wild-pokemon">
      <LocationsChart onShowLocationDetails={loadLocation} />
      {encounterDetails && <EncounterDetailsWrapper encounter={encounterDetails} />}
      {showDetail && <PokemonDetail pokemonId={pokemonEntryId} isWildEncounter={true} />}
    </div>
  );
}
