// src/components/shared/Sidebar.vue
<template>
  <nav class="sidebar">
    <div class="sidebar-header">
      <h1>Dan Stucky</h1>
      <h5>Senior Software Engineer</h5>
    </div>
    <ul class="list-unstyled">
      <router-link to="/about-me" active-class="active">
        <li>Who I Am</li>
      </router-link>
      <router-link to="/dev-projects" active-class="active">
        <li>Dev Projects</li>
      </router-link>
      <router-link to="/pokemon" active-class="active">
        <li>Pokemon Salmon Red</li>
      </router-link>
      <router-link to="/talon" active-class="active">
        <li>Talon Voice</li>
      </router-link>
      <router-link to="/research" active-class="active">
        <li>Genetics Research</li>
      </router-link>
    </ul>
  </nav>
</template>

<script>
export default {};
</script>

<style lang="scss" scoped>
@import url("https://fonts.googleapis.com/css?family=ZCOOL+QingKe+HuangYou&display=swap");

.sidebar {
  width: 250px;
  min-width: 250px;
  height: 100vh;
  z-index: 999;
  border-right: 1px solid rgba(0, 0, 0, 0.2);
  position: sticky;
  top: 0;
  background: #e1ece8;
  color: #63ac99;
  font-family: "ZCOOL QingKe HuangYou", serif;

  .sidebar-header {
    text-align: center;
    padding: 20px;
  }
  a {
    text-decoration: none;

    li {
      color: #63ac99;
      font-size: 24px;
      text-align: left;
      padding: 15px;
      border-bottom: 1px solid rgba(0, 0, 0, 0.2);

      &:hover {
        cursor: pointer;
        background: #63ac99;
        color: white;
      }
    }
  }

  .active li {
    background: #63ac99;
    color: white;
    border: 3px solid #3c8373;

    &:after {
      float: right;
      font-family: "Font Awesome 5 Free";
      font-weight: 900;
      content: "\f101";
    }
  }
}
</style>

// src/components/shared/Sidebar.jsx
import { NavLink } from 'react-router-dom';
import styles from './Sidebar.module.scss';

export default function Sidebar() {
  const getLinkClass = ({ isActive }) => (isActive ? styles.active : '');

  return (
    <nav className={styles.sidebar}>
      <div className={styles.sidebarHeader}>
        <h1>Dan Stucky</h1>
        <h5>Senior Software Engineer</h5>
      </div>
      <ul className="list-unstyled">
        <NavLink to="/about-me" className={getLinkClass}>
          <li>Who I Am</li>
        </NavLink>
        <NavLink to="/dev-projects" className={getLinkClass}>
          <li>Dev Projects</li>
        </NavLink>
        <NavLink to="/pokemon" className={getLinkClass}>
          <li>Pokemon Salmon Red</li>
        </NavLink>
        <NavLink to="/talon" className={getLinkClass}>
          <li>Talon Voice</li>
        </NavLink>
        <NavLink to="/research" className={getLinkClass}>
          <li>Genetics Research</li>
        </NavLink>
      </ul>
    </nav>
  );
}
