// src/components/talon/CheatSheet.vue
<template>
  <h1 class="text-center">Talon Commands Cheatsheet</h1>
  <h5 class="text-center">
    This cheatsheet assumes you have already installed the
    <a href="https://github.com/talonhub/community" target="”_blank”"
      >Community</a
    >
    and
    <a href="https://github.com/david-tejada/rango" target="”_blank”">Rango</a>
    script packages with your talon setup.
  </h5>
  <div class="card">
    <h4 class="card-header">General</h4>
    <div class="card-body">
      <table class="table table-striped table-hover">
        <thead class="thead-dark">
          <tr>
            <th>Voice Command</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Wake Up</td>
            <td>Enable speech recognition.</td>
          </tr>
          <tr>
            <td>Go to sleep</td>
            <td>Disable speech recognition.</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<style lang="scss" scoped>
h1 {
  color: #efefef;
}
h5 {
  color: #efefef;
}
</style>

// src/components/talon/cheatsheet/CheatSheet.jsx
import GeneralCommands from './GeneralCommands'
import KeyboardKeyCommands from './KeyboardKeyCommands'
import DictationCommands from './DictationCommands'
import MouseCommands from './MouseCommands'
import ManageAppWindowCommands from './ManageAppWindowCommands'
import BrowserCommands from './BrowserCommands'
import styles from './CheatSheet.module.scss'

export default function CheatSheet() {
  return (
    <>
      <h1 className={`text-center ${styles.header}`}>Talon Commands Cheatsheet</h1>
      <h5 className={`text-center ${styles.subheader}`}>
        This cheatsheet assumes you have installed the{' '}
        <a href="https://github.com/talonhub/community" target="_blank" rel="noreferrer">Community</a>
        {' '}script package with your talon setup.
      </h5>
      <GeneralCommands className="mb-5 mt-4" />
      <KeyboardKeyCommands className="mb-5" />
      <DictationCommands className="mb-5" />
      <MouseCommands className="mb-5" />
      <ManageAppWindowCommands className="mb-5" />
      <BrowserCommands className="mb-5" />
    </>
  )
}
