// src/components/pokemon/pokedex/PokemonSearch.vue
<template>
  <div class="searchbar">
    <form @input="filterPokedex">
      <input
        v-model="searchValue"
        type="text"
        placeholder="Search Pokemon Name"
      >
    </form>
    <i
      class="fas fa-search"
    />
  </div>
</template>

<script>
import { mapMutations } from 'vuex';
import salmonRedMixin from './../../../mixins/salmonRedMixin';

export default {
  mixins: [salmonRedMixin],
  data() {
    return {
      searchValue: '',
    };
  },
  methods: {
    ...mapMutations([
      'updateSearchResults',
    ]),
    filterPokedex() {
      this.updateSearchResults(this.searchPokedex(this.searchValue));
    },
  },
};
</script>

<style lang="scss" scoped>
  .searchbar {
    position: relative;
    width: 100%;
    max-width: 510px;
    padding-bottom: 20px;
    input {
      border: none;
      outline: none;
      border-radius: 5px;
      padding: 10px 40px 10px 10px;
      width: calc(100% - 50px);
      font-size: 1rem;
      box-shadow: 0 15px 30px rgba(0,0,0,.2),
                  0 10px 10px rgba(0,0,0,.2);
    }
    i {
      position: absolute;
      top: 10px;
      right: 10px;
      font-size: 1.25rem;
      color: rgb(8, 37, 65);
    }
  }
</style>

// src/components/pokemon/pokedex/PokemonSearch.jsx
import { useState } from 'react'
import { usePokemonStore } from '../../../stores/pokemon'
import pokemonService from '../../../services/pokemonService'
import styles from './PokemonSearch.module.scss'

export default function PokemonSearch() {
  const [searchValue, setSearchValue] = useState('')
  const updateSearchResults = usePokemonStore((s) => s.updateSearchResults)

  function filterPokedex(e) {
    setSearchValue(e.target.value)
    updateSearchResults(pokemonService.searchPokedex(e.target.value))
  }

  return (
    <div className={styles.searchbar}>
      <form>
        <input
          type="text"
          value={searchValue}
          onChange={filterPokedex}
          placeholder="Search Pokemon Name"
        />
      </form>
      <i className="fas fa-search" />
    </div>
  )
}
