// src/components/pokemon/PokemonDetail.vue
<template>
  <div class="detail">
    <div class="detail-view" v-if="show">
      <div v-if="pokemon" class="image">
        <img :src="imageUrl + pokemon.id + '.png'" alt="">
      </div>
      <div v-if="pokemon && foundPokemon" class="data">
        <h2>{{ pokemon.name }}</h2>
        <div class="property">
          <div class="left">Base Experience</div>
          <div class="right">{{ pokemon.base_experience }} XP</div>
        </div>
        <div class="property">
          <div class="left">Height</div>
          <div class="right">{{ pokemon.height / 10 }} m</div>
        </div>
        <div class="property">
          <div class="left">Weight</div>
          <div class="right">{{ pokemon.weight / 10 }} kg</div>
        </div>
        <h3>Moves</h3>
        <div class="moves">
          Move 1
        </div>
        <h3>Types</h3>
        <div class="types">
          <div class="type"
            v-for="(value, index) in pokemon.types"
            :key="'value'+index">
            {{ value.type.name }}
          </div>
        </div>
        <h3>Abilities</h3>
        <div class="abilities">
          <div class="ability"
            v-for="(value, index) in pokemon.abilities"
            :key="'value'+index">
            {{ value.ability.name }}
          </div>
        </div>
      </div>
      <h2 v-else>Pokemon not found</h2>
      <button class="close-detail" @click="closeDetail">close</button>
    </div>
    <i v-else class="fas fa-spinner fa-spin"></i>
  </div>
</template>

<script>
import { mapMutations } from 'vuex';

export default {
  props: {
    pokemonId: { required: true },
  },
  data() {
    return {
      show: false,
      pokemon: {},
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/',
      foundPokemon: false,
      basePokemonUrl: 'https://pokeapi.co/api/v2/pokemon/',
    };
  },
  methods: {
    ...mapMutations([
      'closeDetails',
    ]),
    fetchData() {
      const req = new Request(`${this.basePokemonUrl}${this.pokemonId}`);
      fetch(req)
        .then((resp) => {
          if (resp.status === 200) {
            this.foundPokemon = true;
            return resp.json();
          }
          this.foundPokemon = false;
          return { id: 0, name: 'Unknown' };
        })
        .then((data) => {
          this.pokemon = data;
          this.show = true;
        })
        .catch((error) => {
          console.log(error);
        });
    },
    closeDetail() {
      this.closeDetails();
    },
  },
  created() {
    this.fetchData();
  },
};
</script>

<style lang="less" scoped>
  .detail {
    display: flex;
    justify-content: center;
    align-items: flex-start;
    position: fixed;
    top: 0;
    left: 0;
    padding: 90px 10px 10px;
    width: 100%;
    height: 100%;
    background: rgba(0, 0, 0, .7);
    .detail-view {
      display: flex;
      justify-content: center;
      align-items: center;
      flex-direction: column;
      position: relative;
      width: 100%;
      max-width: 510px;
      padding: 50px 0 0;
      background-color: #fff;
      border-radius: 5px;
      box-shadow: 0 15px 30px rgba(0,0,0,.2),
                  0 10px 10px rgba(0,0,0,.2);

      .image {
        display: flex;
        justify-content: center;
        align-items: center;
        position: absolute;
        top: -60px;
        width: 120px;
        height: 120px;
        background-color: #333;
        border-radius: 50%;
        overflow: hidden;
        box-shadow: 0 15px 30px rgba(0,0,0,.2),
                    0 10px 10px rgba(0,0,0,.2);
      }
      h2 {
        text-transform: capitalize;
      }
      .data {
        display: flex;
        justify-content: flex-start;
        align-items: center;
        flex-direction: column;
        width: 100%;
        margin-bottom: 20px;
        .property {
          width: 90%;
          max-width: 400px;
          border-bottom: 1px solid #ccc;
          margin-bottom: 10px;
          .left { float: left; }
          .right { float: right; }
        }
        h3 {
          width: 90%;
          max-width: 400px;
          border-bottom: 1px solid #ccc;
        }
        .types, .abilities {
          display: flex;
          justify-content: flex-start;
          flex-wrap: wrap;
          width: 90%;
          max-width: 400px;
          .type, .ability {
            margin: 0 10px 10px 0;
            padding: 5px 10px;
            border-radius: 20px;
            color: #fff;
            font-size: 1rem;
            letter-spacing: 2px;
            text-transform: capitalize;
            word-wrap: none;
            word-break: keep-all;
          }
          .type { background-color: #0A2E50; }
          .ability { background-color: #C73015; }
        }
      }
      .close-detail {
        opacity: 0.8;
        outline: none;
        border: none;
        border-radius: 5px;
        background-color: #333;
        color: #efefef;
        padding: 10px 20px;
        margin-bottom: 20px;
        font-size: 1.2rem;
        cursor: pointer;

        &:hover {
          opacity: 1.0;
        }
      }
    }
    i {
      font-size: 2rem;
      color: #efefef;
    }
  }
</style>

// src/components/pokemon/pokemon_details/PokemonDetail.jsx
import { useState, useEffect } from 'react';
import { usePokemonStore } from '../../../stores/pokemon';
import PokemonMoves from './PokemonMoves';
import StatsChart from './StatsChart';
import styles from './PokemonDetail.module.scss';

const imageUrl = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/';
const basePokemonUrl = 'https://pokeapi.co/api/v2/pokemon/';

export default function PokemonDetail({ pokemonId, isWildEncounter = false }) {
  const pokemonEncounter = usePokemonStore((s) => s.pokemonEncounter);
  const closeDetails = usePokemonStore((s) => s.closeDetails);

  const [show, setShow] = useState(false);
  const [pokemon, setPokemon] = useState({});
  const [foundPokemon, setFoundPokemon] = useState(false);
  const [showMoves, setShowMoves] = useState(false);
  const [movesVisible, setMovesVisible] = useState(false);
  const [moves, setMoves] = useState([]);

  useEffect(() => {
    setShow(false);
    setPokemon({});
    setFoundPokemon(false);
    setShowMoves(false);
    setMovesVisible(false);
    setMoves([]);

    const req = new Request(`${basePokemonUrl}${pokemonId}`);
    fetch(req)
      .then((resp) => {
        if (resp.status === 200) {
          setFoundPokemon(true);
          return resp.json();
        }
        setFoundPokemon(false);
        return { id: 0, name: 'Unknown' };
      })
      .then((data) => {
        setPokemon(data);
        setShow(true);
      })
      .catch(() => {});
  }, [pokemonId]);

  function handleSlideAnimationEnd() {
    if (!showMoves) {
      setMovesVisible(false);
    }
  }

  function handleContainerClick(e) {
    if (e.target === e.currentTarget) {
      closeDetails();
    }
  }

  function handleToggleMoves() {
    const next = !showMoves;
    setShowMoves(next);
    if (!next) return;

    setMovesVisible(true);
    const salmonRedMoves = [];
    for (const moveData of pokemon.moves) {
      const groupDetails = moveData.version_group_details.find(
        (details) => details.version_group.name === 'black-2-white-2'
      );
      if (groupDetails && groupDetails.move_learn_method.name === 'level-up') {
        salmonRedMoves.push({
          name: moveData.move.name,
          level: groupDetails.level_learned_at,
        });
      }
    }
    setMoves(salmonRedMoves.sort((a, b) => (a.level > b.level ? 1 : -1)));
  }

  return (
    <div className={styles.detailContainer} onClick={handleContainerClick}>
      <div className={styles.detail} onClick={handleContainerClick}>
        {show ? (
          <div className={styles.detailView}>
            <i className={`close-modal-x fas fa-times ${styles.closeModalX}`} onClick={closeDetails} />
            {pokemon && (
              <div className={styles.image}>
                <img src={imageUrl + pokemon.id + '.png'} alt="" />
              </div>
            )}
            {pokemon && foundPokemon ? (
              <div className={styles.data}>
                <h2>{pokemon.name}</h2>
                {isWildEncounter ? (
                  <div className={styles.property}>
                    <div className={styles.left}>Encounter Level</div>
                    <div className={styles.right}>{pokemonEncounter && pokemonEncounter.level}</div>
                  </div>
                ) : (
                  <div className={styles.property} />
                )}
                <StatsChart statsData={pokemon.stats} />
                <div className={`${styles.types} ${styles.detailMajorRow}`}>
                  <h3>Types</h3>
                  <div className={styles.detailMajorRowValues}>
                    {pokemon.types &&
                      pokemon.types.map((value, index) => (
                        <div key={`value${index}`} className={`${styles.type} ${styles.pillContainer}`}>
                          {value.type.name}
                        </div>
                      ))}
                  </div>
                </div>
                <div className={`${styles.abilities} ${styles.detailMajorRow}`}>
                  <h3>Abilities</h3>
                  <div className={styles.detailMajorRowValues}>
                    {pokemon.abilities &&
                      pokemon.abilities.map((value, index) => (
                        <div key={`value${index}`} className={`${styles.ability} ${styles.pillContainer}`}>
                          {value.ability.name}
                        </div>
                      ))}
                  </div>
                </div>
                <div className={styles.detailMajorRow}>
                  <h3>Moves</h3>
                  <div
                    className={`${styles.pillContainer} ${styles.movesBtn}${showMoves ? ` ${styles.activeMoves}` : ''}`}
                    onClick={handleToggleMoves}
                  >
                    Show Moves
                    {!showMoves ? (
                      <i className="fas fa-angle-double-right" />
                    ) : (
                      <i className="fas fa-angle-double-left" />
                    )}
                  </div>
                </div>
              </div>
            ) : (
              <h2>Pokemon not found</h2>
            )}
            <button className={styles.closeDetail} onClick={closeDetails}>
              close
            </button>
          </div>
        ) : (
          <i className="fas fa-spinner fa-spin" />
        )}
        <div
          className={`${styles.slideWrapper}${showMoves ? ` ${styles.slideEnterActive}` : movesVisible ? ` ${styles.slideLeaveActive}` : ''}`}
          onAnimationEnd={handleSlideAnimationEnd}
          onClick={handleContainerClick}
        >
          {movesVisible && <PokemonMoves moves={moves} />}
        </div>
      </div>
    </div>
  );
}
